### ISSUE TITLE
GlideAppModule dependency problems

### ISSUE THREAD

**Issue by jhowens89** [CraZyLegenD/Set-Of-Useful-Kotlin-Extensions-and-Helpers#1]
Hello,

I've been using this library as a reference for a little while and copy/paste-ing certain extension functions when I needed them. Today I decided I would go ahead and just utilize the library as a normal gradle dependency.

However, my application will crash the first time it tries to use GlideApp.with. Details can be found here:

http://bumptech.github.io/glide/doc/configuration.html#avoid-appglidemodule-in-libraries

Is there any way this library could utilize the LibraryGlideModule variant instead or remove the Glide related extensions? Thanks!

**Comment by CraZyLegenD** [comment]
That's because the library itself has a Glide app module, there are few extensions that were written for the Glide loading to utilize their kapt, but I know about that since I use this library in my daily projects and avoid using Glideapp.with cause, there are the extensions I have written for image loading, reference: https://github.com/CraZyLegenD/Set-Of-Useful-Kotlin-Extensions-and-Helpers/tree/master/kotlinextensions/src/main/java/com/crazylegend/kotlinextensions/glide

Thanks for the heads up, i'll fix this in the next version, or you can do so yourself by removing the glideapp module and re-writing the extensions if you want.

**Comment by CraZyLegenD** [comment]
Done, released https://github.com/CraZyLegenD/Set-Of-Useful-Kotlin-Extensions-and-Helpers/releases/tag/1.0.89.16

**Comment by jhowens89** [comment]
Thanks for the fast response, I successfully incorporated the library into my project.

**Comment by CraZyLegenD** [comment]
I just tested the apps I was using, I had GlideApp.with and it worked perfectly without crashes
Since this library doesn't use API but implementation you had to include the glide artifacts for it to work.
But I may just expose everything using api in the next versions
