### ISSUE TITLE
Suggestion for new extensions: Mapbox

### ISSUE THREAD

**Issue by Jeluchu** [CraZyLegenD/Set-Of-Useful-Kotlin-Extensions-and-Helpers#4]
First of all, thank you and congratulations on this wonderful library of Kotlin extensions

I have been seeing that there are Google Maps Extensions, but it would be quite good if some Mapbox were added in the future, since it is another quite powerful map service that is currently used in many projects.

I hope you can add what I said as it would be great. I thank you again

Regards

**Comment by CraZyLegenD** [comment]
Can you share a code sample?

**Comment by CraZyLegenD** [comment]
Also you can fork the library and make a pull request.

**Comment by CraZyLegenD** [comment]
Oh, I see, you're talking about the Mapbox service since their SDK needs to be added I don't think I'll be adding them, as you can notice this library doesn't even have the Google Maps SDK included but has some work-around extensions, sorry about that but if I make Mapbox extensions it'll be a separate library.
